<#
.SYNOPSIS
Inject secrets from OS-level environment variables into .env.local for local dev.
Never stores secrets in the project directory — reads from your user/machine env vars.

.DESCRIPTION
Run this once per terminal session before `npm run dev`.
Reads from Windows/Mac/Linux environment variables set at the OS level
and writes a transient .env.local file (gitignored) that Vite and the
backend pick up automatically.

.PARAMETER Clear
Remove .env.local instead of creating it.

.EXAMPLE
.\scripts\inject-secrets.ps1          # Create .env.local from OS env vars
.\scripts\inject-secrets.ps1 -Clear   # Remove .env.local
#>

param([switch] $Clear)

$projectRoot = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $projectRoot ".env.local"

if ($Clear) {
    if (Test-Path $envFile) {
        Remove-Item $envFile -Force
        Write-Host "[SECURE] .env.local removed." -ForegroundColor Green
    } else {
        Write-Host "[SECURE] No .env.local to remove." -ForegroundColor Yellow
    }
    exit 0
}

# Map of OS env var names to .env.local keys
# Set these in Windows: System Properties > Environment Variables (User variables)
# Or via PowerShell: [Environment]::SetEnvironmentVariable("LOCI_KEY", "value", "User")
$secretMap = @{
    # Supabase
    "LOCI_SUPABASE_URL"                  = "VITE_SUPABASE_URL"
    "LOCI_SUPABASE_ANON_KEY"            = "VITE_SUPABASE_ANON_KEY"
    "LOCI_SUPABASE_FUNCTIONS_URL"       = "VITE_SUPABASE_FUNCTIONS_URL"
    "LOCI_SUPABASE_SERVICE_ROLE_KEY"    = "SUPABASE_SERVICE_ROLE_KEY"

    # CV Extractor
    "LOCI_CV_EXTRACTOR_URL"             = "VITE_CV_EXTRACTOR_URL"
    "LOCI_CV_PARSER_DATABASE_URL"       = "CV_PARSER_DATABASE_URL"

    # Celery / Redis
    "LOCI_CELERY_BROKER_URL"            = "CELERY_BROKER_URL"
    "LOCI_CELERY_RESULT_BACKEND"        = "CELERY_RESULT_BACKEND"

    # LLM Providers
    "LOCI_OPENAI_API_KEY"               = "OPENAI_API_KEY"
    "LOCI_OPENAI_MODEL"                 = "OPENAI_MODEL"
    "LOCI_ANTHROPIC_API_KEY"            = "ANTHROPIC_API_KEY"
    "LOCI_ANTHROPIC_MODEL"              = "ANTHROPIC_MODEL"
    "LOCI_GEMINI_API_KEY"               = "GEMINI_API_KEY"
    "LOCI_GEMINI_MODEL"                 = "GEMINI_MODEL"
    "LOCI_DEEPSEEK_API_KEY"             = "DEEPSEEK_API_KEY"
    "LOCI_DEEPSEEK_MODEL"               = "DEEPSEEK_MODEL"
    "LOCI_LLM_PROVIDER"                 = "LLM_PROVIDER"

    # Redis / Upstash
    "LOCI_UPSTASH_REDIS_REST_URL"       = "UPSTASH_REDIS_REST_URL"
    "LOCI_UPSTASH_REDIS_REST_TOKEN"     = "UPSTASH_REDIS_REST_TOKEN"

    # App
    "LOCI_APP_ORIGIN"                   = "APP_ORIGIN"
    "LOCI_APP_OWNER"                    = "VITE_APP_OWNER"
}

$missing = @()
$written = @()

$lines = @("# .env.local — generated by scripts/inject-secrets.ps1", "# DO NOT commit. Regenerate each session.", "")

foreach ($osVar in $secretMap.Keys | Sort-Object) {
    $value = [Environment]::GetEnvironmentVariable($osVar, "User")
    if (-not $value) {
        $value = [Environment]::GetEnvironmentVariable($osVar, "Machine")
    }

    $envKey = $secretMap[$osVar]

    if ($value) {
        $lines += "$envKey=$value"
        $written += $envKey
    } else {
        $missing += $osVar
    }
}

if ($written.Count -eq 0) {
    Write-Host "[SECURE] No LOCI_* environment variables found." -ForegroundColor Red
    Write-Host ""
    Write-Host "Set them in Windows (User variables recommended):"
    Write-Host "  [Environment]::SetEnvironmentVariable('LOCI_SUPABASE_URL', 'https://...', 'User')"
    Write-Host ""
    Write-Host "Or set them per-session in your terminal:"
    Write-Host "  `$env:LOCI_SUPABASE_URL = 'https://...'"
    Write-Host ""
    Write-Host "After setting, re-run: .\scripts\inject-secrets.ps1"
    exit 1
}

Set-Content -Path $envFile -Value ($lines -join "`r`n") -Encoding UTF8

Write-Host "[SECURE] .env.local written with $($written.Count) variables:" -ForegroundColor Green
foreach ($key in $written) {
    Write-Host "  + $key" -ForegroundColor Cyan
}

if ($missing.Count -gt 0) {
    Write-Host ""
    Write-Host "[INFO] $($missing.Count) optional OS vars not set (using defaults):" -ForegroundColor Yellow
    foreach ($var in $missing) {
        Write-Host "  - $var" -ForegroundColor DarkYellow
    }
}

Write-Host ""
Write-Host "[READY] Run 'npm run dev' to start with injected secrets." -ForegroundColor Green
